### ISSUE TITLE
Container requires additional packages to install

### ISSUE THREAD

**Issue by dismine** [teeks99/gcc-ubuntu-docker#3]
Hello.

I tried to use your image to test my code with GCC 11. And it seems it is not fully configured for use. I forced to add these packages: _dialog apt-utils locales locales-all_ to my build dependencies. Without them, installing packages hangs with error: _debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)_.

The list of packages may be incorrect. I just tried these four before it starts working.

**Comment by teeks99** [comment]
What are you trying to use it for/build?

**Comment by dismine** [comment]
Qt5 application.

**Comment by teeks99** [comment]
The `dialog` package seems to be relevant to user input...that doesn't seem like it would work in docker. Am I missing something?

**Comment by dismine** [comment]
As i understood, it will with environment variable _DEBIAN_FRONTEND=noninteractive_.

**Comment by dismine** [comment]
Here are my logs:

https://api.cirrus-ci.com/v1/task/5366372503912448/logs/install.log
https://api.cirrus-ci.com/v1/task/6172571285585920/logs/install.log

Whole history of my builds is here https://cirrus-ci.com/github/dismine/valentina/develop

**Comment by teeks99** [comment]
Yikes!

`After this operation, 247 MB of additional disk space will be used.`

That seems like it will bloat the image a lot. It looks like this is mostly in `locales-all` what is that needed for? Could it be something you add in your build process?

**Comment by dismine** [comment]
I don't know what you mean. I decided to tell you about this situation because with official GCC image i don't need to install anything additional.

**Comment by teeks99** [comment]
Which GCC image are you referring to? None of those are part of the default Ubuntu image, nor installed when adding gcc. I'm not opposed to adding them, but I think the locales-all would need a pretty strong use-case, to add that much space to the image.

**Comment by dismine** [comment]
Currently i use _teeks99/gcc-ubuntu:lates_. But i don't tell you that _locales-all_ is what you need to add. It is just one of four i tried. I can try to test with just _dialog_.

**Comment by dismine** [comment]
I have made tests. Apparently, all i need is _DEBIAN_FRONTEND=noninteractive_

With the environment variable: https://api.cirrus-ci.com/v1/task/6063487974637568/logs/install.log
Without the environment variable: https://api.cirrus-ci.com/v1/task/6331364061478912/logs/install.log

I hope it will help.
